name: mic
channels:
- defaults
- conda-forge
dependencies:
- python=3.6*
- click
- cytoolz
- h5py
- matplotlib
- networkx
- numpy
- pandas
- bokeh>=0.13
- pip
- pymongo=3*
- scikit-image
- scikit-learn
- scipy
- setuptools
- six
- toolz
- imageio
- ipyvolume
- pip:
  - coverage>=4.0
  - pytest>=2.8
  - pytest-cov>=2.2
  - sh>=1.11

